# Generated by Django 4.2.5 on 2023-10-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
                ('aadhar_no', models.IntegerField()),
                ('e_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
